---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-java
  labels:
    app: backend-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-java
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend-java
    spec:
      containers:
        - name: backend-java
          image: yyarynich/provedcode-backend-java:1.0
          ports:
            - containerPort: 9000
              protocol: TCP
          env:
            - name: DB_LOGIN
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: APP_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: APP_PASSWORD
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: DB_URL
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: APP_MODE
            - name: BUCKET
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: BUCKET
            - name: S3_ACCESS_KEY 
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: S3_ACCESS_KEY
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: S3_SECRET_KEY
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: S3_REGION
          resources:
            limits:
              memory: 500Mi
            requests:
              memory: 500Mi
              cpu: 500m
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
