---
apiVersion: v1
kind: Service
metadata:
  name: frontend-react
  namespace: provedcode
spec:
  selector:
    app: frontend-react
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
 