Vagrant.configure("2") do |config|
  config.vm.provider "vmware_desktop" do |vm|
    vm.force_vmware_license = "workstation"
    vm.vmx["memsize"] = "2048"
    vm.vmx["numvcpus"] = "1"
  end

  def define_machine(config, name, box, ip, playbook)
    config.vm.define name do |machine|
      machine.vm.box = box
      machine.vm.network "private_network", ip: ip

      machine.vm.provision "ansible" do |ansible|
        ansible.playbook = playbook
        ansible.inventory_path = "hosts"
        ansible.limit = name
      end
    end
  end

  define_machine(config, "db", "bento/rockylinux-9", "192.168.100.13", "provisioning/db.yml")
  define_machine(config, "server", "bento/debian-12", "192.168.100.12", "provisioning/server.yml")
  define_machine(config, "web", "bento/ubuntu-24.04", "192.168.100.11", "provisioning/web.yml")
end