---
apiVersion: v1
kind: Service
metadata:
  name: backend-java
  namespace: provedcode
  annotations:
spec:
  selector:
    app: backend-java
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600