name: Terraform code validation
on:
  pull_request:
    branches:
      - main
    paths:
      - "terraform/eks/**/*"
    
jobs:
  validation:
    name: Terraform code validation
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        working-directory: terraform/eks
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -recursive

    - name: Terraform init
      id: init
      run: terraform init -no-color

    - name: Terraform validate
      id: validate
      run: terraform validate -no-color


  scan:
    name: Security scan with checkov
    permissions:
      contents: read
      security-events: write 
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform/eks
          compact: true
          quiet: true
          soft_fail: true
          output_format: cli,sarif
          output_file_path: console,results.sarif
        
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
